# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "mosquitto-exporter-unstable-${version}";
  version = "2019-05-21";
  rev = "0ac92b543dc5af5dc9f63280fd64eb7d958055e4";

  goPackagePath = "github.com/sapcc/mosquitto-exporter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/sapcc/mosquitto-exporter";
    sha256 = "1n4k60y50x3b0m2lgghcr027m44xrlg25hnaxj9mv2lzsmwaag13";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
