# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "mosquitto-exporter-unstable-${version}";
  version = "0.5.0";
  rev = "v${version}";

  goPackagePath = "github.com/sapcc/mosquitto-exporter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/sapcc/mosquitto-exporter";
    sha256 = "0hg0vdsn3h3giary1mwd6n4hafmc9kwjs7lvn58w7p587rq8qa3m";
  };

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
