# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.zfs.extraPools = [ "ein-data" ];

  fileSystems."/" =
    { device = "fastroot/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" =
    { device = "fastroot/docker";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "fastroot/home";
      fsType = "zfs";
    };

  fileSystems."/home/benley" =
    { device = "fastroot/home/benley";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-id/nvme-Samsung_SSD_980_PRO_1TB_S5P2NG0NB04378K-part6";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-id/nvme-Samsung_SSD_980_PRO_1TB_S5P2NG0NB04378K-part2";
      fsType = "vfat";
    };

  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/017d2803-feac-4a80-bc1e-85b015e52ff0"; }
  #   ];

  # nix.maxJobs = lib.mkDefault 8;

  # hardware.video.hidpi.enable = lib.mkDefault true;
}
