#!/usr/bin/env bash
set -e
trap "rm -f .git/tags.$$" EXIT
ctags=ctags
[[ -e /usr/local/bin/ctags ]] && ctags=/usr/local/bin/ctags
$ctags -R -f ".git/tags.$$" \
  --exclude=".git" \
  --exclude="bazel-*" \
  --exclude="result" \
  --exclude=".stack-work" \
  --tag-relative
mv ".git/tags.$$" .git/tags
